[package]
name = "slingshot"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"
description = "SystemVerilog LSP powered by Slang"
readme = "README.md"
license = "MPL-2.0"
# for now
publish = false

[dependencies]
tower-lsp = "0.19.0"
tokio = { version = "1.28.2", features = ["full"] }

[build-dependencies]
bindgen = "0.66.0"
cmake = "0.1.50"

# Somewhere, somehow, in the C++ side of things, "-flto=thin" is being appended to the compile flags.
# I don't know WHO is responsible for adding that (probably Boost), it ain't me, so we have no choice but to force
# LTO everywhere for interop.
[profile.dev]
lto = "thin"

[profile.release]
lto = "thin"
