[package]
name = "slingshot"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"
description = "SystemVerilog LSP powered by Slang"
readme = "README.md"
license = "MPL-2.0"
# for now
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-lsp = "0.19.0"
tokio = { version = "1.28.2", features = ["full"] }
cmake = "0.1.50"
bindgen = "0.66.0"
