/*
 * Copyright (c) 2023 Matt Young.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package slingshot.completion

import slingshot.parsing.CompletionTypes
import slingshot.parsing.SvDocument


/**
 * Completion result returned by a [CompletionProvider]
 * @param activeModule name of current module being edited, if we are in one, else null
 * @param recommendations parsed recommendations generated by CursorParseTreeVisitor
 */
data class CompletionResult(
    val document: SvDocument,
    val recommendations: List<CompletionTypes>,
    val activeModule: String?
)